# File: .github/dependabot.yaml
version: 2
updates:
  # 1. Python Dependencies
  - package-ecosystem: "pip"
    # Point to root where pyproject.toml lives
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    groups:
      production-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
